# Generated by Django 4.1.2 on 2024-05-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(db_column='idArea', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(max_length=25, verbose_name='Razón')),
                ('reporte', models.FileField(upload_to='excel_files/')),
                ('fecha_Emision', models.DateField(verbose_name='Fecha Emisión')),
                ('margen_fecha_datos', models.CharField(max_length=40, verbose_name='Margen de fecha de datos')),
                ('id_area', models.ForeignKey(db_column='idArea', on_delete=django.db.models.deletion.CASCADE, to='reporteria.area', verbose_name='Área')),
            ],
        ),
    ]
