# Generated by Django 4.1.2 on 2024-05-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock_producto', models.IntegerField()),
                ('fecha_despacho', models.DateField()),
                ('proveedor', models.CharField(max_length=100)),
                ('adquisiciones', models.TextField()),
                ('postventa', models.TextField()),
                ('contabilidad', models.TextField()),
            ],
        ),
    ]
