# Generated by Django 4.1.2 on 2024-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='razon',
            field=models.CharField(max_length=60, verbose_name='Razón'),
        ),
    ]
