# Generated by Django 5.0.6 on 2024-05-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta',
            new_name='Reporte',
        ),
    ]
