# Generated by Django 5.0.6 on 2024-05-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0002_rename_venta_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='precio_producto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
