# Generated by Django 5.0.6 on 2024-06-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0003_reporte_precio_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
