# Generated by Django 5.0.6 on 2024-06-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporteria', '0004_delete_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_de_despachos', models.IntegerField()),
                ('entregados', models.IntegerField()),
                ('no_entregados', models.IntegerField()),
            ],
        ),
    ]
